#!/bin/bash

# arguments:
#   $1 = oci: registry
#   $2 = name of command
#   $3 = version tag
# ARGS = extra args to pass to apptainer
# ${@} = remaining args to pass to the command

# Halt on error
set -e

# get the location of this file - sif folder should be a peer
THIS="$(dirname "$(readlink -f "$0")")"

# for local use we may need to create the sif folder
sif_folder=${THIS}/sif
if [[ ! -d ${THIS} ]] ; then
    mkdir ${sif_folder}
fi

sif_name=sif/$2:$3.sif
oci_name=$1/$2:$3

# get the sif if it does not exist
if [[ ! -f ${sif_name} ]]; then
    apptainer pull ${sif_name} docker://${oci_name}
else
    # touch the sif to indicate usage - may be used for cleanup algorithm
    touch ${sif_name}
fi

# add mounts for all available useful folders
mounts=/home
for i in /scratch /dls /dls_sw ; do
    if [[ -d ${i} ]] ; then
        mounts=${mounts},${i}
    fi
done

opts="-e --env DISPLAY=${DISPLAY}"

apptainer run -B ${mounts} ${opts} ${sif_name}
