#!/bin/bash

# arguments:
#   $1 = oci: registry
#   $2 = name of command
#   $3 = version tag
# ARGS = extra args to pass to apptainer
# ${@} = remaining args to pass to the command

cif_name=$1:$3.cif
oci_name=$1/$2:$3

# get the cif if it does not exist
if [[ ! -f ${cif_name} ]]; then
    apptainer pull ${cif_name} ${oci_name}
else
    # touch the cif to indicate usage - may be used for cleanup algorithm
    touch ${cif_name}
fi

# add mounts for all available useful folders
mounts=/home
for i in /scratch /dls /dls_sw ; do
    if [[ -d ${i} ]] ; then
        mounts=${mounts},${i}
fi

opts="-e --env DISPLAY=${DISPLAY}"

apptainer run -B ${mounts} ${opts} ${cif_name}
